### ISSUE TITLE
Get rid of global eval()

### ISSUE THREAD

**Issue by ojack** [hydra-synth/hydra-synth#139]
Follow up from:
https://github.com/hydra-synth/hydra-synth/pull/136

Is it possible to remove global eval() without causing iframes to break?

Where is the sandbox actually being used / why is it causing breaks in the iframes?

**Comment by msawired** [comment]
To help with this, here is the example error from native browser console:
```

caught DOMException: Blocked a frame with origin "https://iframe.example.com" from accessing a cross-origin frame.
    at eval (eval at r (https://cdn.jsdelivr.net/npm/hydra-synth@1.3.25/dist/hydra-synth.min.js:7:145337), <anonymous>:4:25)
    at r (https://cdn.jsdelivr.net/npm/hydra-synth@1.3.25/dist/hydra-synth.min.js:7:145348)
    at Object.addToContext (https://cdn.jsdelivr.net/npm/hydra-synth@1.3.25/dist/hydra-synth.min.js:7:145265)
    at a.add (https://cdn.jsdelivr.net/npm/hydra-synth@1.3.25/dist/hydra-synth.min.js:7:103179)
    at https://cdn.jsdelivr.net/npm/hydra-synth@1.3.25/dist/hydra-synth.min.js:7:103089
    at Array.forEach (<anonymous>)
    at new a (https://cdn.jsdelivr.net/npm/hydra-synth@1.3.25/dist/hydra-synth.min.js:7:103072)
    at new m (https://cdn.jsdelivr.net/npm/hydra-synth@1.3.25/dist/hydra-synth.min.js:7:130655)
    at createHydra (blob:https://iframe.example.com/myScript:5:14)
    ...
```

For example, you would see this error if you embed iframe.example.com in an iframe on www.example.com.
