### ISSUE TITLE
a function without () nested inside another like blend/modulate/mult - cause hard crash...

### ISSUE THREAD

**Issue by ffd8** [hydra-synth/hydra-synth#150]
This is probably not an issue, since one should know to always use `()`, buuut discovered a unique way to crash hard, requiring a refresh of the browser (context, has come up with beginner forgetting to write `()`, also in an attempt to autocompile on keyup:

this is fine:
`osc().modulate(osc().kaleid()).out()`

this crashes hard:
`osc().modulate(osc().kaleid).out()`
(same thing when using `blend`, `mult`, etc.. anything that can contain additional sources)

it produces the following error on repeat in the console:
```
VM461:340 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Output.draw (eval at compile (hydra-synth.js:951:191), <anonymous>:340:32)
    at E.stats [as draw] (hydra-synth.js:1027:338)
    at Output.tick (hydra-synth.js:4330:8)
    at HydraRenderer.tick (hydra-synth.js:3291:19)
    at Engine.emit (hydra-synth.js:154:5)
    at Engine.tick (hydra-synth.js:801:10)
draw @ VM461:340
E.stats @ hydra-synth.js:1027
Output.tick @ hydra-synth.js:4330
tick @ hydra-synth.js:3291
emit @ hydra-synth.js:154
Engine.tick @ hydra-synth.js:801
requestAnimationFrame (async)
module.exports @ hydra-synth.js:869
Engine.tick @ hydra-synth.js:798
hydra-synth.js:1201 ERROR TypeError: Cannot read properties of undefined (reading 'push')
    at sourceClass.<computed> (hydra-synth.js:1459:25)
    at typedArg.value (hydra-synth.js:1191:40)
    at Output.draw (eval at compile (hydra-synth.js:951:191), <anonymous>:339:11)
    at E.stats [as draw] (hydra-synth.js:1027:338)
    at Output.tick (hydra-synth.js:4330:8)
    at HydraRenderer.tick (hydra-synth.js:3291:19)
    at Engine.emit (hydra-synth.js:154:5)
    at Engine.tick (hydra-synth.js:801:10)
```

Once correcting the bug and trying to recompile it produces the following:
```
[.WebGL-0x1240158b600] GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.
about:srcdoc:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```
which then requires a restart.

Any ideas? It's the coders fault for causing it, but I wonder if there's a try/catch situation for the nesting that might be able to prevent it from requiring a full refresh?

**Comment by geikha** [comment]
maybe, since functions are also objects in JS, we can add some flag to the GlslSoruce functions, for example `func.isTex = true`. Then at the point where Hydra interprets arguments sent to function, if the function has this flag, it throws an error, if it doesn't have this flag, it tries to assign it as an uniform as usual

**Comment by ojack** [comment]
Oooh maybe this can happen in the argument formatting part of hydra-synth,
will look into it

**Comment by ojack** [comment]
Just ran into this again and it is brutal!! 

```
osc(3, 0.05, 0.8).modulate(osc(4).r, 0.4).out()
```

**Comment by bodobraegger** [comment]
@ojack : worked on this with a tagging system, now we get descriptive error messages with missing parentheses hints.

**Comment by ojack** [comment]
@bodobraegger love it, thank you!!
